version: '3'

services:
  manager:
    container_name: 'nginx-proxy-manager'
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # - '21:21' # FTP
    environment:
      VIRTUAL_HOST: 'lbs.iny.su'
      DB_MYSQL_HOST: 'db'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: 'lbs'
      DB_MYSQL_PASSWORD: 'lbs'
      DB_MYSQL_NAME: 'lbs'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-size: '5m'
        max-file: '3'

  portainer:
    container_name: 'portainer'
    image: portainer/portainer
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=portainer.iny.su
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    networks:
      nginx-proxy:
    logging:
      driver: "json-file"
      options:
        max-size: '5m'
        max-file: '3'

  db:
    container_name: 'mariadb-aria'
    image: 'jc21/mariadb-aria:latest'
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'lbs'
      MYSQL_DATABASE: 'lbs'
      MYSQL_USER: 'lbs'
      MYSQL_PASSWORD: 'lbs'
      MARIADB_AUTO_UPGRADE: '1'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-size: '5m'
        max-file: '3'

  phpmyadmin:
    container_name: 'phpmyadmin'
    image: phpmyadmin/phpmyadmin
#    ports:
#      - '80:80'
    environment:
      - PMA_ARBITRARY=1
    links:
      - db:mysql
    networks:
      - nginx-proxy
    logging:
      driver: "json-file"
      options:
        max-size: '5m'
        max-file: '3'

networks:
  nginx-proxy:
    driver: bridge
