version: '3.8'

services:
  db:
    image: postgres:13
    container_name: matrix_db
    restart: unless-stopped
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
      LC_COLLATE: "C"
      LC_CTYPE: "C"
      POSTGRES_USER: matrix
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: synapse
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - matrix_net

  synapse:
    image: matrixdotorg/synapse:latest
    container_name: matrix_synapse
    restart: unless-stopped
    depends_on:
      - db
    expose:
      - "8008"
    volumes:
      - ./synapse-data:/data
      - ./synapse-data/media_store:/data/media_store
      - ./synapse-data/uploads:/data/uploads
      - ./homeserver.yaml:/data/homeserver.yaml
    environment:
      - UID=991
      - GID=991
      - SYNAPSE_SERVER_NAME=web.fiv.dev
      - SYNAPSE_REPORT_STATS=no
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - VIRTUAL_HOST=matrix.web.fiv.dev  # Изменено на поддомен
      - VIRTUAL_PORT=8008
      - LETSENCRYPT_HOST=matrix.web.fiv.dev
      - LETSENCRYPT_EMAIL=yesfedor.go@gmail.com
    networks:
      - matrix_net
      - default

  coturn:
    image: coturn/coturn:latest
    container_name: matrix_coturn
    restart: unless-stopped
    volumes:
      - ./turnserver.conf:/etc/turnserver.conf:ro
    command: turnserver -c /etc/turnserver.conf
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "5349:5349/tcp"
    networks:
      - matrix_net

  element:
    image: vectorim/element-web:latest
    container_name: matrix_element
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./element-config.json:/app/config.json
    environment:
      - VIRTUAL_HOST=web.fiv.dev  # Основной домен для Element
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=web.fiv.dev
      - LETSENCRYPT_EMAIL=your@email.com
    networks:
      - matrix_net
      - default

networks:
  default:
    external:
      name: nginx-proxy
  matrix_net:
    driver: bridge
