version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3333:3306
    volumes:
      - ./db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 3334:80
    environment:
      - PMA_ARBITRARY=1
    links:
      - db:mysql

volumes:
  db_data:
