version: '3'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3306:3306'
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      nginx-proxy:

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '80:80'
    environment:
      - PMA_ARBITRARY=1
    links:
      - db:mysql
    networks:
      - nginx-proxy

volumes:
  db_data:

networks:
  nginx-proxy:
    external: true
